### PR TITLE
Updated to latest stable vert.x and kotlin version

### PR DESCRIPTION
**Pull request by nikos**
Making use of of vert.x 3.5.0 release and Kotlin 1.2.0

### CODE REVIEW

**Review by dgoetsch — COMMENTED** [review]
Is this to make the websocket API test runnable upon checkout?

**Comment by nikos** [comment]
Yes, with no extra setup (milestone/sandbox repo) I was not able to retrieve the artefacts right after cloning.

**Comment by dgoetsch** [comment]
I still don't think this will compile, we ended up omitting ping handler from the imementation since the only cction is immediately reply with pong

**Comment by nikos** [comment]
Well, here on my side it is compiling and even running :-)

```
gradle clean web-socket-unified:run

w: /Users/niko/sandbox/vertx/vertx-web-socket-test/web-socket-client/src/main/kotlin/dev/yn/playground/web/socket/WebSocketServer.kt: (27, 32): Parameter 'message' is never used
w: /Users/niko/sandbox/vertx/vertx-web-socket-test/web-socket-server/src/main/kotlin/dev/yn/playground/web/socket/server/App.kt: (9, 9): Variable 'vertx' is never used
w: /Users/niko/sandbox/vertx/vertx-web-socket-test/web-socket-server/src/main/kotlin/dev/yn/playground/web/socket/server/App.kt: (19, 17): Name shadowed: vertx
w: /Users/niko/sandbox/vertx/vertx-web-socket-test/web-socket-server/src/main/kotlin/dev/yn/playground/web/socket/server/tyrus/EchoWebSocketEndPoint.kt: (44, 20): Parameter 'message' is never used
w: /Users/niko/sandbox/vertx/vertx-web-socket-test/web-socket-server/src/main/kotlin/dev/yn/playground/web/socket/server/vertx/WebSocketEndpoint.kt: (58, 32): Parameter 'message' is never used

> Task :web-socket-unified:run
Dec 12, 2017 1:45:09 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8025]
Dec 12, 2017 1:45:09 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Dec 12, 2017 1:45:09 PM org.glassfish.tyrus.server.Server start
INFO: WebSocket Registered apps: URLs all start with ws://localhost:8025
Dec 12, 2017 1:45:09 PM org.glassfish.tyrus.server.Server start
INFO: WebSocket server started.
Dec 12, 2017 1:45:11 PM dev.yn.playground.web.socket.server.tyrus.EchoWebSocketEndPoint
INFO: opening session e4e9200f-6503-4e39-88fd-3f3a13cebef4
[client-01] writing to server
Dec 12, 2017 1:45:11 PM dev.yn.playground.web.socket.server.tyrus.EchoWebSocketEndPoint
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 recevied text message: Message to start!
[client-01] received: Welcome!
Dec 12, 2017 1:45:11 PM dev.yn.playground.web.socket.server.tyrus.EchoWebSocketEndPoint
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 received pong message
Dec 12, 2017 1:45:11 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 restarting pong timer
Dec 12, 2017 1:45:12 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: pinging e4e9200f-6503-4e39-88fd-3f3a13cebef4
Dec 12, 2017 1:45:12 PM dev.yn.playground.web.socket.server.tyrus.EchoWebSocketEndPoint
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 received pong message
Dec 12, 2017 1:45:12 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 restarting pong timer
Dec 12, 2017 1:45:13 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: pinging e4e9200f-6503-4e39-88fd-3f3a13cebef4
Dec 12, 2017 1:45:13 PM dev.yn.playground.web.socket.server.tyrus.EchoWebSocketEndPoint
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 received pong message
Dec 12, 2017 1:45:13 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 restarting pong timer
Dec 12, 2017 1:45:14 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: pinging e4e9200f-6503-4e39-88fd-3f3a13cebef4
Dec 12, 2017 1:45:14 PM dev.yn.playground.web.socket.server.tyrus.EchoWebSocketEndPoint
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 received pong message
Dec 12, 2017 1:45:14 PM dev.yn.playground.web.socket.server.tyrus.SessionVerticle
INFO: session e4e9200f-6503-4e39-88fd-3f3a13cebef4 restarting pong timer
```

**Comment by dgoetsch** [comment]
Oh cool. Checked again and that line is commented out.

**Pull request merged**
